### ISSUE TITLE
can't start mode in emacs 31.5

### ISSUE THREAD

**Issue by merisbahti** [leafOfTree/svelte-ts-mode#11]
I get this error on start:
```
funcall-interactively: Symbol’s value as variable is void: js--treesit-font-lock-settings
```

**Comment by Ziqi-Yang** [comment]
It's fixed in `emacs-master` branch.

```emacs-lisp
(use-package svelte-ts-mode
  :after eglot
  :ensure (:host github :repo "leafOfTree/svelte-ts-mode" :branch "emacs-master"))
```

**Comment by GokhanPolat** [comment]
The problem still occurs even if the 'emacs-master' branch is used.
